on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n firstcontainerregistry2020 -g firstcontainerregistry2020861f-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n firstcontainerregistry2020 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n firstcontainerregistry2020 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n firstcontainerregistry2020 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: firstcontainerregistry2020.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t firstcontainerregistry2020.azurecr.io/myakscluster2020:${{ github.sha }}
        docker push firstcontainerregistry2020.azurecr.io/myakscluster2020:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myakscluster2020_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster20208e13 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster20208e13`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster20208e13
        container-registry-url: firstcontainerregistry2020.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myakscluster20208e13
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          firstcontainerregistry2020.azurecr.io/myakscluster2020:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth